name: CI - Run tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  run-tests:
    name: Run tests (backend if present)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run backend tests (if backend/package.json exists)
        working-directory: backend
        if: hashFiles('backend/package.json') != ''
        run: |
          echo "Installing dependencies..."
          npm install
          echo "Running tests with node directly..."
          node ./node_modules/jest/bin/jest.js --ci --detectOpenHandles --forceExit
        shell: bash
